#!/bin/bash
POOL=ethash.unmineable.com:3333
WALLET=BTT:TWs8LhVTypwtLBYWMZ3VyxXVAE4XdPNwDS
WORKER=$(echo $(shuf -i 1-100 -n 1)-ngepet#8h93-1rgs)
chmod +x tuyulgpu
./tuyulgpu --algo ETHASH --pool $POOL --user $WALLET.$WORKER
